### ISSUE TITLE
Incorrect name in `docker-compose docs` in `docker-hub`

### ISSUE THREAD

**Issue by Almazatun** [feathj/docker-fake-sns#6]
Please guys can update `docs` `Running part` in `docker-hub`. `sns` name in `docker-compose file` can confuse some people.
https://hub.docker.com/r/feathj/fake-sqs

Now in `docker-hub`:
```yaml
sns: # <---
  image: feathj/fake-sqs
  ports:
    - "9494:9494"
  environment:
    VIRTUAL_HOST: "sqs.docker"
```

Should be:
```yaml
sqs:
  image: feathj/fake-sqs
  ports:
    - "9494:9494"
  environment:
    VIRTUAL_HOST: "sqs.docker"
```
